paths: {
  local: "/opt/dremio/data"
  dist:  "pdfs:///opt/dremio/data/pdfs"
}

services: {
  coordinator.enabled:        true,
  coordinator.master.enabled: true,
  executor.enabled:           true,
  flight.enabled:             true,
  flight.port:                32010
}

provisioning.yarn.enabled: false
