paths: {
  # the local path for dremio to store data
  local: "/opt/dremio/data"
  # the distributed storage location
  dist: "pdfs:///opt/dremio/data/pdfs"
}

services: {
  coordinator.enabled: true,
  coordinator.master.enabled: true,
  executor.enabled: true,
  flight.enabled: true,
  flight.port: 32010
}

provisioning.yarn.enabled: false

debug: {
  # required for path style S3 access (MinIO)
  s3.use.path.style.requests: true
}
